// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iShare.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN


#pragma mark - IShareRoot

@interface IShareRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Login_m

typedef GPB_ENUM(Login_m_FieldNumber) {
  Login_m_FieldNumber_Username = 1,
  Login_m_FieldNumber_Password = 2,
};

// The request message contain username and password
@interface Login_m : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *password;

@end

#pragma mark - Sign_m

typedef GPB_ENUM(Sign_m_FieldNumber) {
  Sign_m_FieldNumber_Username = 1,
  Sign_m_FieldNumber_Password = 2,
  Sign_m_FieldNumber_Email = 3,
};

@interface Sign_m : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *password;

@property(nonatomic, readwrite, copy) NSString *email;

@end

#pragma mark - Inf

typedef GPB_ENUM(Inf_FieldNumber) {
  Inf_FieldNumber_Information = 1,
};

@interface Inf : GPBMessage

@property(nonatomic, readwrite, copy) NSString *information;

@end

#pragma mark - Repeated_string

typedef GPB_ENUM(Repeated_string_FieldNumber) {
  Repeated_string_FieldNumber_ContentArray = 1,
};

@interface Repeated_string : GPBMessage

// |contentArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *contentArray;

@end

#pragma mark - User_detail

typedef GPB_ENUM(User_detail_FieldNumber) {
  User_detail_FieldNumber_Username = 1,
  User_detail_FieldNumber_Email = 2,
  User_detail_FieldNumber_FriendsArray = 3,
};

@interface User_detail : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *email;

// |friendsArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *friendsArray;

@end

#pragma mark - Share_inf

typedef GPB_ENUM(Share_inf_FieldNumber) {
  Share_inf_FieldNumber_Creater = 1,
  Share_inf_FieldNumber_Amount = 2,
  Share_inf_FieldNumber_Type = 3,
  Share_inf_FieldNumber_PaidBy = 4,
  Share_inf_FieldNumber_Data_p = 5,
  Share_inf_FieldNumber_Note = 6,
  Share_inf_FieldNumber_Image = 7,
  Share_inf_FieldNumber_MembersArray = 8,
  Share_inf_FieldNumber_MembersCount = 9,
  Share_inf_FieldNumber_BillId = 10,
  Share_inf_FieldNumber_PaidStatus = 11,
};

@interface Share_inf : GPBMessage

@property(nonatomic, readwrite, copy) NSString *creater;

@property(nonatomic, readwrite, copy) NSString *amount;

@property(nonatomic, readwrite, copy) NSString *type;

@property(nonatomic, readwrite, copy) NSString *paidBy;

@property(nonatomic, readwrite, copy) NSString *data_p;

@property(nonatomic, readwrite, copy) NSString *note;

@property(nonatomic, readwrite, copy) NSString *image;

// |membersArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *membersArray;

@property(nonatomic, readwrite) int32_t membersCount;

@property(nonatomic, readwrite, copy) NSString *billId;

@property(nonatomic, readwrite, copy) NSString *paidStatus;

@end

#pragma mark - Bill_request

typedef GPB_ENUM(Bill_request_FieldNumber) {
  Bill_request_FieldNumber_Username = 1,
  Bill_request_FieldNumber_Start = 2,
  Bill_request_FieldNumber_Amount = 3,
};

@interface Bill_request : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *start;

@property(nonatomic, readwrite, copy) NSString *amount;

@end

#pragma mark - Syn_data

typedef GPB_ENUM(Syn_data_FieldNumber) {
  Syn_data_FieldNumber_Friend_p = 1,
  Syn_data_FieldNumber_Bill = 2,
  Syn_data_FieldNumber_Delete_p = 3,
  Syn_data_FieldNumber_Request = 4,
};

@interface Syn_data : GPBMessage

@property(nonatomic, readwrite, copy) NSString *friend_p;

@property(nonatomic, readwrite, copy) NSString *bill;

@property(nonatomic, readwrite, copy) NSString *delete_p;

@property(nonatomic, readwrite, copy) NSString *request;

@end

#pragma mark - HelloRequest

typedef GPB_ENUM(HelloRequest_FieldNumber) {
  HelloRequest_FieldNumber_Name = 1,
};

// The request message containing the user's name.
@interface HelloRequest : GPBMessage

@property(nonatomic, readwrite, copy) NSString *name;

@end

#pragma mark - HelloReply

typedef GPB_ENUM(HelloReply_FieldNumber) {
  HelloReply_FieldNumber_Message = 1,
};

// The response message containing the greetings
@interface HelloReply : GPBMessage

@property(nonatomic, readwrite, copy) NSString *message;

@end

#pragma mark - Image

typedef GPB_ENUM(Image_FieldNumber) {
  Image_FieldNumber_Name = 1,
  Image_FieldNumber_Data_p = 2,
};

@interface Image : GPBMessage

@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite, copy) NSData *data_p;

@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_RequestId = 1,
  Request_FieldNumber_Sender = 2,
  Request_FieldNumber_Receiver = 3,
  Request_FieldNumber_Type = 4,
  Request_FieldNumber_Content = 5,
  Request_FieldNumber_Response = 6,
  Request_FieldNumber_RequestDate = 7,
  Request_FieldNumber_ResponseDate = 8,
  Request_FieldNumber_IgnoreFrom = 9,
  Request_FieldNumber_IgnoreTo = 10,
};

@interface Request : GPBMessage

@property(nonatomic, readwrite, copy) NSString *requestId;

@property(nonatomic, readwrite, copy) NSString *sender;

@property(nonatomic, readwrite, copy) NSString *receiver;

@property(nonatomic, readwrite, copy) NSString *type;

@property(nonatomic, readwrite, copy) NSString *content;

@property(nonatomic, readwrite, copy) NSString *response;

@property(nonatomic, readwrite, copy) NSString *requestDate;

@property(nonatomic, readwrite, copy) NSString *responseDate;

@property(nonatomic, readwrite, copy) NSString *ignoreFrom;

@property(nonatomic, readwrite, copy) NSString *ignoreTo;

@end

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_RequestId = 1,
  Response_FieldNumber_Sender = 2,
  Response_FieldNumber_Receiver = 3,
  Response_FieldNumber_Response = 4,
  Response_FieldNumber_ResponseDate = 5,
};

@interface Response : GPBMessage

@property(nonatomic, readwrite, copy) NSString *requestId;

@property(nonatomic, readwrite, copy) NSString *sender;

@property(nonatomic, readwrite, copy) NSString *receiver;

@property(nonatomic, readwrite, copy) NSString *response;

@property(nonatomic, readwrite, copy) NSString *responseDate;

@end

#pragma mark - IgnoreMessage

typedef GPB_ENUM(IgnoreMessage_FieldNumber) {
  IgnoreMessage_FieldNumber_RequestLogId = 1,
  IgnoreMessage_FieldNumber_User = 2,
};

@interface IgnoreMessage : GPBMessage

@property(nonatomic, readwrite, copy) NSString *requestLogId;

@property(nonatomic, readwrite, copy) NSString *user;

@end

#pragma mark - BillPayment

typedef GPB_ENUM(BillPayment_FieldNumber) {
  BillPayment_FieldNumber_BillId = 1,
  BillPayment_FieldNumber_PaidStatus = 2,
};

@interface BillPayment : GPBMessage

@property(nonatomic, readwrite, copy) NSString *billId;

@property(nonatomic, readwrite, copy) NSString *paidStatus;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
