// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iShare.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN


#pragma mark - IShareRoot

@interface IShareRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Login_m

typedef GPB_ENUM(Login_m_FieldNumber) {
  Login_m_FieldNumber_Username = 1,
  Login_m_FieldNumber_Password = 2,
};

// The request message contain username and password
@interface Login_m : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *password;

@end

#pragma mark - Sign_m

typedef GPB_ENUM(Sign_m_FieldNumber) {
  Sign_m_FieldNumber_Username = 1,
  Sign_m_FieldNumber_Password = 2,
  Sign_m_FieldNumber_Email = 3,
};

@interface Sign_m : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *password;

@property(nonatomic, readwrite, copy) NSString *email;

@end

#pragma mark - Inf

typedef GPB_ENUM(Inf_FieldNumber) {
  Inf_FieldNumber_Information = 1,
};

@interface Inf : GPBMessage

@property(nonatomic, readwrite, copy) NSString *information;

@end

#pragma mark - Repeated_string

typedef GPB_ENUM(Repeated_string_FieldNumber) {
  Repeated_string_FieldNumber_ContentArray = 1,
};

@interface Repeated_string : GPBMessage

// |contentArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *contentArray;

@end

#pragma mark - User_detail

typedef GPB_ENUM(User_detail_FieldNumber) {
  User_detail_FieldNumber_Username = 1,
  User_detail_FieldNumber_Email = 2,
  User_detail_FieldNumber_FriendsArray = 3,
};

@interface User_detail : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *email;

// |friendsArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *friendsArray;

@end

#pragma mark - Share_inf

typedef GPB_ENUM(Share_inf_FieldNumber) {
  Share_inf_FieldNumber_Creater = 1,
  Share_inf_FieldNumber_Amount = 2,
  Share_inf_FieldNumber_Type = 3,
  Share_inf_FieldNumber_Account = 4,
  Share_inf_FieldNumber_Data_p = 5,
  Share_inf_FieldNumber_Note = 6,
  Share_inf_FieldNumber_Image = 7,
  Share_inf_FieldNumber_MembersArray = 8,
  Share_inf_FieldNumber_MembersCount = 9,
  Share_inf_FieldNumber_BillId = 10,
};

@interface Share_inf : GPBMessage

@property(nonatomic, readwrite, copy) NSString *creater;

@property(nonatomic, readwrite, copy) NSString *amount;

@property(nonatomic, readwrite, copy) NSString *type;

@property(nonatomic, readwrite, copy) NSString *account;

@property(nonatomic, readwrite, copy) NSString *data_p;

@property(nonatomic, readwrite, copy) NSString *note;

@property(nonatomic, readwrite, copy) NSString *image;

// |membersArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *membersArray;

@property(nonatomic, readwrite) int32_t membersCount;

@property(nonatomic, readwrite, copy) NSString *billId;

@end

#pragma mark - Bill_request

typedef GPB_ENUM(Bill_request_FieldNumber) {
  Bill_request_FieldNumber_Username = 1,
  Bill_request_FieldNumber_Start = 2,
  Bill_request_FieldNumber_Amount = 3,
};

@interface Bill_request : GPBMessage

@property(nonatomic, readwrite, copy) NSString *username;

@property(nonatomic, readwrite, copy) NSString *start;

@property(nonatomic, readwrite, copy) NSString *amount;

@end

#pragma mark - Syn_data

typedef GPB_ENUM(Syn_data_FieldNumber) {
  Syn_data_FieldNumber_Friend_p = 1,
  Syn_data_FieldNumber_Bill = 2,
  Syn_data_FieldNumber_Delete_p = 3,
};

@interface Syn_data : GPBMessage

@property(nonatomic, readwrite, copy) NSString *friend_p;

@property(nonatomic, readwrite, copy) NSString *bill;

@property(nonatomic, readwrite, copy) NSString *delete_p;

@end

#pragma mark - HelloRequest

typedef GPB_ENUM(HelloRequest_FieldNumber) {
  HelloRequest_FieldNumber_Name = 1,
};

// The request message containing the user's name.
@interface HelloRequest : GPBMessage

@property(nonatomic, readwrite, copy) NSString *name;

@end

#pragma mark - HelloReply

typedef GPB_ENUM(HelloReply_FieldNumber) {
  HelloReply_FieldNumber_Message = 1,
};

// The response message containing the greetings
@interface HelloReply : GPBMessage

@property(nonatomic, readwrite, copy) NSString *message;

@end

#pragma mark - Image

typedef GPB_ENUM(Image_FieldNumber) {
  Image_FieldNumber_Name = 1,
  Image_FieldNumber_Data_p = 2,
};

@interface Image : GPBMessage

@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite, copy) NSData *data_p;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
